version: '3.8'

services:
  web:
    build: .
    command: bash -c "python dynamodb.py && python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb
    env_file:
      - .env

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
